version: '3.8'

services:
  web:
    build: .
    image: cicd-app:latest
    container_name: cicd-app
    ports:
      - 5000:80
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mongo:latest
    restart: unless-stopped
